repos:
- repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
  hooks:
  - id: pylint
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.10
- repo: https://github.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8